version: '2'
services:
  backend:
    build: ./backend/
    command: rm tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: development
    ports:
      - '4000:3000'
    volumes:
       - ./backend:/backend
  frontend:
    image: node:8.11
    working_dir: /frontend
    ports:
      - "4001:8080"
    command: yarn start
    restart: always
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
volumes:
  node_modules:
    driver: local

