version: '2'
services:
  backend:
    build: ./backend/
    command: bash ./bin/start.sh
    environment:
      - "RAILS_ENV=development"
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_USER
      - DATABASE_PASSWORD
      - TWITTER_KEY
      - TWITTER_SECRET
      - SECRET_KEY_BASE
    ports:
      - '4000:4000'
    links:
      - db
    stdin_open: true
    volumes:
      - ./backend:/backend
      - bundle:/backend/vendor/cache
  frontend:
    image: node:8.11
    working_dir: /frontend
    ports:
      - "4001:8080"
    command: yarn start
    restart: always
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules
  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  twitter-bot:
    build: ./twitter-bot/
    environment:
      - TWITTER_KEY
      - TWITTER_SECRET
      - ACCESS_TOKEN
      - ACCESS_SECRET
volumes:
  node_modules:
    driver: local
  bundle:
    driver: local
