version: '3'
volumes:  
  postgres_data: {} 
services:  
  backend:    
    build:      
      context: .      
      dockerfile: ./backend/Dockerfile.prod    
    environment:
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_USER
      - DATABASE_PASSWORD
      - TWITTER_KEY
      - TWITTER_SECRET
      - SECRET_KEY_BASE
    depends_on:      
      - db  
  db:    
    image: postgres    
    volumes:      
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
  nginx:    
    build:      
      context: .      
      dockerfile: ./nginx/Dockerfile  
    depends_on:      
      - backend 
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /var/www/api.tagmaru.me:/var/www/api.tagmaru.me
    ports:      
      - 80:80
      - 443:443
